image: java:8

variables:
  TEST_RUNNER_URI: "/run-test.cfm"

before_script:
  - git clone --depth 1 https://github.com/foundeo/cfmatrix.git cfmatrix
  - bash cfmatrix/install.sh
  
#add a pipeline for each CFENGINE you want to test
lucee5: 
  variables:
    CFENGINE: ""
  script:
    - bash cfmatrix/run.sh

cf11:
  variables:
    CFENGINE: "adobe@11"
  script:
    - bash cfmatrix/run.sh
