language: java
sudo: false
jdk:
- openjdk8
env:
  global:
    - TEST_RUNNER_URI=/test/run.cfm
  matrix:
    - CFENGINE=lucee@4.5
    - CFENGINE=lucee@5
    - CFENGINE=adobe@10
    - CFENGINE=adobe@11
    - CFENGINE=adobe@2016
    - CFENGINE=adobe@2018
before_install:
- git clone --depth 1 https://github.com/foundeo/cfmatrix.git cfmatrix
install:
- bash ./cfmatrix/install.sh
script:
- bash ./cfmatrix/run.sh
